feat: melhorias do pipeline

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -20,27 +20,27 @@ pipeline {
         stage('Transfer Jar to Deploy Folder') {
             steps {
                 dir('backend') {
-                     script {
-                        sh "docker stop nexum-back || true"
+                    if (fileExists("$APP_PATH$APP_JAVA")) {
+                        sh "rm $APP_PATH$APP_JAVA"
                     }
-                    sh "rm $APP_PATH$APP_JAVA || true"
                     sh "cp target/$APP_JAVA $APP_PATH"
                     sh "chmod +x $APP_PATH$APP_JAVA"
-                    sh "docker rm nexum-back || true"
                 }
             }
         }
-        stage('Deploy') {
-            steps {
-                script {
-                    if (isDockerInstalled()) {
-                        sh "docker run -d -p 8000:8000 --network nexum-network --name nexum-back -v $APP_PATH$APP_JAVA:/app/$APP_JAVA nexum-image-back"
-                    } else {
-                        echo 'Docker is not installed. Skipping deployment.'
-                    }
+        stage('Docker Deploy') {
+            script {
+                stopAndRemoveContainer()
+                removeImage()
+                def buildSuccess = buildDockerImage()
+                if (buildSuccess) {
+                    createDockerContainer()
+                } else {
+                    error  "Error: Failed to build Docker image"
                 }
             }
         }
+
     }
 }
 
@@ -51,4 +51,42 @@ def isDockerInstalled() {
     } catch (Exception e) {
         return false
     }
+}
+
+def stopAndRemoveContainer() {
+    sh "docker stop nexum-back || true"
+    sh "docker rm nexum-back || true"
+}
+
+def removeImage() 
+{
+    sh "docker rmi nexum-back-image || true"
+}
+
+def buildDockerImage() {
+    def imageName = 'nexum-back-image'
+    def dockerfilePath = 'nexum/backend/Dockerfile'
+    def dockerBuildContext = 'nexum/backend'
+
+    def dockerBuildCommand = "docker build -t ${imageName} -f ${dockerfilePath} ${dockerBuildContext}"
+    def buildOutput = sh(returnStdout: true, returnStatus: true, script: dockerBuildCommand).trim()
+
+    if (buildOutput == 0) {
+        return true
+    } else {
+        echo "Erro: Falha ao criar a imagem do Docker. Saída do comando:\n${buildOutput}"
+        return false
+    }
+}
+
+
+def createDockerContainer() {
+    def containerName = 'nexum-back'
+    def imageName = 'nexum-back-image'
+    def APP_JAVA = 'backend-0.0.1-SNAPSHOT.jar'
+    def APP_PATH = '/home/ubuntu/deploy/'
+    
+    def createContainerCommand = "docker run -d -p 8000:8000 --network nexum-network --name ${containerName} -v ${APP_PATH}${APP_JAVA}:/app/${APP_JAVA}  ${imageName}"
+    sh createContainerCommand
+    
 }
